
  apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: mongodb-blog
  spec:
    selector:
      matchLabels:
        app: mongo  #) same as mongo-service.yml spec:selector:app:- 
        #) mtlb unn pod ko pakdunga jinka label mongo hoga  
    serviceName: mongodb-service
    replicas: 1
    template:
      metadata:
        labels:
          app: mongo #) same as mongo-service.yml spec:selector:app:--
          #) mtlb vo pod naunga jinka label mongo hoga
      spec:
        containers:
        - name: blog-mongo
          image: mongo:6
          ports:
          - containerPort: 27017
            name: web
          volumeMounts:
          - name: mongo-data
            mountPath: /data/db
    volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
  
